version: '3.8'

services:
  # website:
  #   image: heimatfront-web:latest
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - MONGO_CONNECTION_STRING=mongodb://database:27017
  #   depends_on:
  #     - database
  #   networks:
  #     - app-network

  database:
    image: mongo:latest
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - ./data/db:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
